apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: aegis-deepspeed-train-
  namespace: aegis
spec:
  entrypoint: train-package-sign
  arguments:
    parameters:
      - name: experiment-name
        value: "aegis-demo"
      - name: mlflow-tracking-uri
        value: "http://mlflow.aegis.svc.cluster.local:5000"
      - name: object-store-bucket
        value: "REPLACE_WITH_BUCKET"
  templates:
    - name: train-package-sign
      dag:
        tasks:
          - name: submit-pytorchjob
            template: submit-pytorchjob
          - name: wait-for-completion
            template: wait-for-completion
            dependencies: [submit-pytorchjob]
          - name: package-and-sign
            template: package-and-sign
            dependencies: [wait-for-completion]

    - name: submit-pytorchjob
      script:
        image: ghcr.io/rsinghunjan/aegis-train:latest
        command: [sh]
        source: |
          set -euo pipefail
          cat <<'PYT' > /tmp/pytorchjob.yaml
          apiVersion: kubeflow.org/v1
          kind: PyTorchJob
          metadata:
            name: aegis-deepspeed-{{workflow.name}}
            namespace: aegis
          spec:
            cleanPodPolicy: None
            pytorchReplicaSpecs:
              Master:
                replicas: 1
                restartPolicy: OnFailure
                template:
                  spec:
                    containers:
                      - name: pytorch
                        image: ghcr.io/rsinghunjan/aegis-train:latest
                        command: ["python","/workspace/training/train_deepspeed.py","--out-dir","/workspace/model_registry/demo-models/cifar_deepspeed/0.1","--max-epochs","1"]
                        resources:
                          limits:
                            nvidia.com/gpu: 1
              Worker:
                replicas: 1
                restartPolicy: OnFailure
                template:
                  spec:
                    containers:
                      - name: pytorch
                        image: ghcr.io/rsinghunjan/aegis-train:latest
                        command: ["sleep","3600"]
          PYT
          kubectl apply -f /tmp/pytorchjob.yaml
          echo "Submitted PyTorchJob."

    - name: wait-for-completion
      script:
        image: bitnami/kubectl:latest
        command: [sh]
        source: |
          set -euo pipefail
          JOBNAME="aegis-deepspeed-{{workflow.name}}"
          for i in $(seq 1 240); do
            status=$(kubectl -n aegis get pytorchjob "$JOBNAME" -o jsonpath='{.status.conditions[-1].type}' 2>/dev/null || true)
            echo "Status: $status"
            if [ "$status" = "Succeeded" ]; then
              echo "PyTorchJob Succeeded"
              exit 0
            fi
            if [ "$status" = "Failed" ]; then
              echo "PyTorchJob Failed" >&2
              kubectl -n aegis get pods -l job-name="$JOBNAME" -o wide || true
              exit 1
            fi
            sleep 15
          done
          echo "Timeout waiting for PyTorchJob" >&2
          exit 2

    - name: package-and-sign
      script:
        image: ghcr.io/rsinghunjan/aegis-tools:latest
        command: [sh]
        source: |
          set -euo pipefail
          OUTDIR="/workspace/model_registry/demo-models/cifar_deepspeed/0.1"
          ARTIFACT="/workspace/artifacts/cifar-deepspeed-0.1.tar.gz"
          mkdir -p /workspace/artifacts
          echo "Packaging artifact..."
          python3 /workspace/scripts/make_deterministic_archive.py "$OUTDIR" "$ARTIFACT"
          echo "Calling package/sign helper..."
          /workspace/scripts/package_and_sign_vault.sh "$OUTDIR" "$ARTIFACT"
          echo "Uploading artifacts to s3..."
          if [ -n "${OBJECT_STORE_BUCKET:-}" ]; then
            aws s3 cp "$ARTIFACT" "s3://${OBJECT_STORE_BUCKET}/model-archives/demo/{{workflow.name}}/$(basename $ARTIFACT)"
            aws s3 cp "${ARTIFACT}.sig.json" "s3://${OBJECT_STORE_BUCKET}/model-archives/demo/{{workflow.name}}/$(basename ${ARTIFACT}.sig.json)"
          else
            echo "OBJECT_STORE_BUCKET not set; artifact left in workspace"
          fi
