  8
  9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
 23
 24
 25
 26
 27
 28
 29
 30
 31
 32
 33
 34
 35
#!/usr/bin/env bash
#
# Run the scanner + auto_refactor, commit refactors/ directory to a branch and open a PR (requires gh CLI & git auth).
# Usage: ./scripts/create_refactor_branch.sh owner/repo
set -euo pipefail

REPO=${1:-}
BRANCH=${2:-refactor/sdk-to-storageclient-candidates}
OUTDIR=${3:-refactors-candidates}

if [ -z "$REPO" ]; then
  echo "Usage: $0 owner/repo [branch-name] [outdir]" >&2
  exit 2
fi

echo "Running strict scanner (non-strict mode to list findings)..."
python3 scripts/scan_cloud_sdk_usage.py || true

echo "Generating candidate refactors..."
python3 scripts/auto_refactor.py --root . --out-dir "$OUTDIR"

if [ ! -d "$OUTDIR" ]; then
  echo "No refactors produced; nothing to push." >&2
  exit 0
fi

git checkout -b "$BRANCH"
git add "$OUTDIR"
git commit -m "chore(refactor): add candidate .refactored.py files for replacing direct cloud SDK usage"
git push -u origin "$BRANCH"

echo "Opening PR via gh..."
gh pr create --repo "$REPO" --title "refactor: replace direct cloud SDK usage (candidate files)" --body "This PR contains candidate .refactored.py files generated by scripts/auto_refactor.py. Review the files and apply the suggested replacements, run tests, then merge."

echo "PR opened from branch $BRANCH. Review the refactors in $OUTDIR."
scripts/create_refactor_branch.sh
