
name: "example-tf-model"
platform: "tensorflow_savedmodel"
max_batch_size: 8
input [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [ 28, 28, 1 ]
  }
]
output [
  {
    name: "probs"
    data_type: TYPE_FP32
    dims: [ 10 ]
  }
]
instance_group [
  { kind: KIND_CPU }  # change to KIND_GPU for GPU backends
]
